Lesson 7 more ajax features
pavel-sazonov/QnA pull request #5
Opened 2018-05-20 09:01 UTC by pavel-sazonov

2018-05-20 09:05 UTC, pavel-sazonov commented
Не могу разобраться, почему после редактирования при повторном нажатии на ссылку Edit не появляется форма редактирования, а заново грузится questions#show.

Так же два варианта отмены старого лучшего ответа при назначении нового в контроллере ответов. Не знаю, как правильнее.

2018-05-20 09:31 UTC, vkurennov requested changes

2018-05-20 09:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @question.answers.update(best: false)
1. Этому всему не место в контроллере, потому что это бизнес-логика. А бизнес-логика должна быть в моделях. А здесь только вызываются нужные методы модели.
2. т.к. у тебя есть несколько апдейтов, то их нужно обернуть в [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html)
3. В этой строке лучше использовать `update_all`

2018-05-20 09:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    # первый вариант сброса старого лучшего ответа (вынести его в метод модели ответа)
Любой из вариантов нужно выносить в метод модели. В целом, можешь оставить тот, который больше нравится, они в принципе равнозначны.

2018-05-20 09:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.update(best: true) if current_user.author_of?(@question)
То есть, сначала мы принудительно сбрасываем существующий лучший ответ, а потом может оказаться, что запрос не от автора вопроса и мы не назначим новый лучший?

2018-05-20 09:31 UTC, vkurennov commented on spec/rails_helper.rb
> +  Capybara.default_max_wait_time = 5
Это стоит вынести в acceptance_helper

2018-05-21 07:33 UTC, vkurennov requested changes

2018-05-21 07:33 UTC, vkurennov commented on app/views/questions/_question.html.slim
> +div class="question"
Это можно записать просто как  `.question`

2018-05-21 07:33 UTC, vkurennov commented on app/assets/javascripts/answers.coffee
> +  $('.edit-answer-link').click (e) ->
Ссылка на редактирование перестает работать, потому что мы заменяем все элементы ответа (т.е. это новые DOM-элементы), а к ним не прикрепелен обработчик. Он прикрепляется только к тем, которые есть в момент загрузки страницы. Чтобы это пофиксить, нужно немного по-другому повесить обработчик:

`$('.answers').on 'click', '.edit-answer-link', (e) ->`

так у тебя будет обработчик вешаться на статический элемент `.answers`,  но при клике будет еще и фильтр по `.edit-answer-link` отрабатывать и в итоге, это будет работать даже для динамически добавленных/измененных элементов.

2018-05-21 07:33 UTC, vkurennov commented on app/assets/javascripts/questions.coffee
> +  $('.edit-question-link').click (e) ->
Тут аналогично, нужно заменить обработчик на  `$('.question').on 'click', '.edit-question-link', (e) ->`

2018-05-21 07:33 UTC, vkurennov commented on app/views/answers/update.js.erb
> +$('#answer_<%= @answer.id %>').html('<%= j render @answer %>');
Чтобы не менялся номер элемента, попробуй сделать следующее:

1. вместо html используй replaceWith, в этом случае сам элемент, который в селекторе не меняется. Но из-за твоего паршала ответа, тут скорее всего, начнут появляться вложенные списки, что тоже не очень хорошо.
2. Поэтому лучше изменить структуру самого парашала, вместо li с классом для ответа сделай так:

```
li
  div id="answer_#{answer.id}" class="answer"
```

тогда при замене блока, li не будет меняться, будет меняться только вложенный div

2018-05-21 07:33 UTC, vkurennov commented on config/routes.rb
> +  patch '/answers/:id/best', to: 'answers#set_best', as: 'best_answer'
Почитай [как добавлять кастомные экшены](http://guides.rubyonrails.org/routing.html#adding-more-restful-actions)

2018-05-21 07:33 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(another_answer).to be_best
По идее, в юнит-тестах действует правило "один тест - один expect", поэтому этот тест нужно разделить минимум на 2:

1. просто проверяем, что ответ у которого вызыван метод, стал лучшим
2. Если есть старый лучший ответ, то он становится не лучшим.

2018-05-21 08:29 UTC, pavel-sazonov commented on app/views/answers/update.js.erb
> +$('#answer_<%= @answer.id %>').html('<%= j render @answer %>');
поменял, но проблема осталась
вот так выглядит в браузере после редактирования второго ответа:
![screen shot 2018-05-21 at 11 06 27](https://user-images.githubusercontent.com/25341920/40297939-24303360-5cea-11e8-86ba-6b19a77767fb.png)

2018-05-21 16:11 UTC, vkurennov approved these changes

2018-05-21 16:44 UTC, merged